### ISSUE TITLE
[tracking] updates for norns 2.0

### ISSUE THREAD

**Issue by pq** [monome/docs#64]
tracking issue for doc updates corresponding w/ [norns 2.0](https://github.com/monome/norns/milestone/4)

---

bits to review:

- [ ] studies
  - [ ] [study 1](https://github.com/monome/docs/blob/master/docs/norns/study-1.md)
  - [ ] [study 2](https://github.com/monome/docs/blob/master/docs/norns/study-2.md)
  - [ ] [study 3](https://github.com/monome/docs/blob/master/docs/norns/study-3.md)
  - [ ] [study 4](https://github.com/monome/docs/blob/master/docs/norns/study-4.md)
  - [ ] [study 5](https://github.com/monome/docs/blob/master/docs/norns/study-5.md)
- [ ] [update instructions](https://github.com/monome/docs/blob/master/docs/norns/update/index.md)
- [ ] [legend](https://github.com/monome/docs/blob/master/docs/norns/norns-legend.pdf)
- [ ] [faq](https://github.com/monome/norns/wiki/FAQ)
- [ ] [roadmap](https://github.com/monome/norns/wiki/roadmap)

**Comment by tehn** [comment]
also:

- [ ] script gathering/sharing (how to manage `dust`, lines wiki thread for directory of scripts)
- [ ] script repos and docs (ie, move `mlr` to its own repo, update docs)
